# Generated by Django 4.0.5 on 2022-09-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('Encuesta_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Encuesta_FechaCompletado', models.DateField()),
                ('Encuesta_Detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('Formulario_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Formulario_Titulo', models.CharField(max_length=40)),
                ('Formulario_FechaCreacion', models.DateField()),
                ('Formulario_Detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pregunta',
            fields=[
                ('TipoPregunta_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TipoPregunta_Descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Usuario_Correo', models.CharField(max_length=40)),
                ('Usuario_Contrasena', models.CharField(max_length=40)),
                ('Usuario_Rol', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('Resultado_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Resultado_Diagnostico', models.CharField(max_length=80)),
                ('Resultado_Descripcion', models.CharField(max_length=80)),
                ('Resultado_Recomendacion', models.CharField(max_length=140)),
                ('Resultado_Fecha', models.DateField()),
                ('Encuesta_Encuesta_Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('Pregunta_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Pregunta_Interrogante', models.CharField(max_length=80)),
                ('Pregunta_Nivel', models.CharField(max_length=40)),
                ('Tipo_Pregunta_TipoPregunta_Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.tipo_pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Paciente_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Paciente_Nombre', models.CharField(max_length=40)),
                ('Paciente_Apellidos', models.CharField(max_length=40)),
                ('Paciente_Edad', models.CharField(max_length=2)),
                ('Paciente_Departamento', models.CharField(max_length=40)),
                ('Paciente_Telefono', models.CharField(max_length=9)),
                ('Paciente_DNI', models.CharField(max_length=8)),
                ('Usuario_Usuario_Codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta_X_Pregunta',
            fields=[
                ('EncuestaPregunta_Codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Formulario_Formulario_Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.formulario')),
                ('Pregunta_Pregunta_Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Formulario_Formulario_Codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.formulario'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Paciente_Paciente_Codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.paciente'),
        ),
    ]
