# Generated by Django 4.1 on 2022-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='Usuario_Usuario_Codigo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Paciente_Contrasena',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Paciente_Correo',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Paciente_Rol',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Resultado_Descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
