# Generated by Django 4.1 on 2022-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_paciente_usuario_usuario_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_Codigo',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
