# Generated by Django 4.1 on 2022-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_paciente_paciente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='Encuesta_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encuesta_x_pregunta',
            name='EncuestaPregunta_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='Formulario_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='Pregunta_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Resultado_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_pregunta',
            name='TipoPregunta_Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
