# Generated by Django 4.1 on 2022-09-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_encuesta_encuesta_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Paciente_Usuario',
            field=models.CharField(default='', max_length=40),
        ),
    ]
