# Generated by Django 4.1 on 2022-09-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_paciente_paciente_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_Codigo',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
