# Generated by Django 4.1 on 2022-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_paciente_paciente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='Resultado_por_palabras_depresivas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='Resultado_por_parametros',
            field=models.FloatField(default=0),
        ),
    ]
