# Generated by Django 4.0.5 on 2022-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_resultado_resultado_por_palabras_depresivas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='Resultado_escala_por_palabras_depresivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='Resultado_escala_por_parametros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='Resultado_escala_total',
            field=models.IntegerField(default=0),
        ),
    ]
