# Generated by Django 4.1 on 2022-10-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_resultado_resultado_escala_por_palabras_depresivas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='Encuesta_FechaCompletado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='Formulario_FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Resultado_Fecha',
            field=models.DateTimeField(),
        ),
    ]
