# Generated by Django 4.1 on 2022-10-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_encuesta_encuesta_fechacompletado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_X_Pregunta',
            fields=[
                ('FormularioPregunta_Codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='encuesta_x_pregunta',
            name='Formulario_Formulario_Codigo',
        ),
        migrations.RemoveField(
            model_name='encuesta_x_pregunta',
            name='Pregunta_Pregunta_Codigo',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='Encuesta_Encuesta_Codigo',
        ),
        migrations.AddField(
            model_name='formulario',
            name='Paciente_Paciente_Codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='Resultado_Resultado_Codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.resultado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='Encuesta_X_Pregunta',
        ),
        migrations.AddField(
            model_name='formulario_x_pregunta',
            name='Formulario_Formulario_Codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.formulario'),
        ),
        migrations.AddField(
            model_name='formulario_x_pregunta',
            name='Pregunta_Pregunta_Codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.pregunta'),
        ),
        migrations.AddField(
            model_name='formulario_x_pregunta',
            name='Resultado_Resultado_Codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.resultado'),
        ),
    ]
