# Generated by Django 4.1 on 2022-10-30 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_formulario_x_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='Resultado_Resultado_Codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.resultado'),
        ),
    ]
