# Generated by Django 4.0.5 on 2022-11-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_alter_formulario_resultado_resultado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_x_pregunta',
            name='Resultado_Resultado_Codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.resultado'),
        ),
    ]
