# Generated by Django 4.0.5 on 2022-11-05 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_formulario_x_pregunta_formulario_x_pregunta_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_x_pregunta',
            name='Formulario_X_Pregunta_FechaActualizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formulario_x_pregunta',
            name='Formulario_X_Pregunta_FechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 0, 56, 43, 733478)),
        ),
    ]
