# Generated by Django 4.0.5 on 2022-11-08 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_formulario_x_pregunta_formulario_x_pregunta_fechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_x_pregunta',
            name='Formulario_X_Pregunta_FechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 22, 10, 14, 873391)),
        ),
    ]
