# Generated by Django 4.1 on 2022-11-12 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_alter_formulario_x_pregunta_formulario_x_pregunta_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_x_pregunta',
            name='Formulario_X_Pregunta_FechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 22, 24, 45, 5132)),
        ),
    ]
