# Generated by Django 4.1 on 2022-11-15 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_resultado_resultado_tipo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_x_pregunta',
            name='Formulario_X_Pregunta_FechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 22, 19, 54, 715915)),
        ),
    ]
